### PR TITLE
tools: follow up update after tss tpm2b change

### PR DESCRIPTION
**Pull request by tstruk**
TSS changed the TPM2B structure definitions.
This update reflects this change.

### CODE REVIEW

**Comment by tstruk** [comment]
@martinezjavier Yes, this is blocked until @flihp will get to this https://github.com/intel/tpm2-abrmd/pull/240

**Comment by flihp** [comment]
intel/tpm2-abrmd#240 has been merged

**Comment by martinezjavier** [comment]
@flihp great, thanks!

@tstruk still the first commit from PR #609 is needed. I'll update my branch dropping the workaround now that you have proposed a real fix for the API changes.

**Comment by williamcroberts** [comment]
@tstruk @martinezjavier FYI I am pulling this locally and will get the tools building against latest tss/master and merge back and then look at the CI failures on the package grabs. @martinezjavier after that ill start looking at 3.X

**Comment by martinezjavier** [comment]
@williamcroberts sounds good to me.

**Comment by williamcroberts** [comment]
merged on master, currently, locally test_tpm2_activatecredential is failing:
```
$ ./test.sh test_tpm2_activecredential.sh 
/ERROR: ActivateCredential failed. TPM Error:0x1df
tpm2_activatecredential -Q -H 0x8101000a -k 0x81010009 -f mkcred.out -o actcred.out on line 62 failed: 1
-Test left files around, found: .test_tpm2_activecredential.sh.swp
test_tpm2_activecredential.sh ... FAILED
Tests passed: 0
Tests Failed: 1
Fail summary:

test_tpm2_activecredential.sh
```
Closing this

**Pull request closed without merging**
