### PR TITLE
3.x

### PR DESCRIPTION
**Pull request by williamcroberts**

### CODE REVIEW

**Comment by williamcroberts** [comment]
@martinezjavier got the issue with activatecred test... getpubak is dumping an xxd compliant hex dump out for key name and its causing the loadedkey to be wrong....

I'm looking at yaml output for that by default... since it has multiple items.

Im thinking for 4.0 it would be nice to have all outputs in yaml when sent to stdout.... and drop the -f yaml option and just say, we only care about 1 format...

**Comment by martinezjavier** [comment]
@williamcroberts great, then I guess you will update this branch with the proper fix and drop the commit that disables the test.

BTW this branch doesn't build, you need to squash the following fixup to "tpm2_[make|activate]credential: serialization fix":

```
diff --git a/tools/tpm2_activatecredential.c b/tools/tpm2_activatecredential.c
index e54300893a74..920915c0447f 100644
--- a/tools/tpm2_activatecredential.c
+++ b/tools/tpm2_activatecredential.c
@@ -112,19 +112,19 @@ static bool read_cert_secret(const char *path, TPM2B_ID_OBJECT *cred,
         goto out;
     }
 
-    result = files_read_bytes(fp, cred->credential, cred->t.size);
+    result = files_read_bytes(fp, cred->t.credential, cred->t.size);
     if (!result) {
         LOG_ERR("Could not read credential data");
         goto out;
     }
 
-    result = files_read_16(fp, &secret->size);
+    result = files_read_16(fp, &secret->t.size);
     if (!result) {
         LOG_ERR("Could not read secret size");
         goto out;
     }
 
-    result = files_read_bytes(fp, secret->secret, secret->size);
+    result = files_read_bytes(fp, secret->t.secret, secret->t.size);
     if (!result) {
         LOG_ERR("Could not write secret data");
         goto out;
diff --git a/tools/tpm2_makecredential.c b/tools/tpm2_makecredential.c
index 05b82137ea01..646f9a260de2 100644
--- a/tools/tpm2_makecredential.c
+++ b/tools/tpm2_makecredential.c
@@ -89,19 +89,19 @@ static bool write_cred_and_secret(const char *path, TPM2B_ID_OBJECT *cred,
         goto out;
     }
 
-    result = files_write_bytes(fp, cred->credential, cred->t.size);
+    result = files_write_bytes(fp, cred->t.credential, cred->t.size);
     if (!result) {
         LOG_ERR("Could not write credential data");
         goto out;
     }
 
-    result = files_write_16(fp, secret->size);
+    result = files_write_16(fp, secret->t.size);
     if (!result) {
         LOG_ERR("Could not write secret size");
         goto out;
     }
 
-    result = files_write_bytes(fp, secret->secret, secret->size);
+    result = files_write_bytes(fp, secret->t.secret, secret->t.size);
     if (!result) {
         LOG_ERR("Could not write secret data");
         goto out;
```

**Comment by martinezjavier** [comment]
You can see the build failure in the Travis CI job: https://travis-ci.org/intel/tpm2-tools/jobs/299907349

**Comment by martinezjavier** [comment]
@williamcroberts also, there are some fixes in master that never made it to the 3.X branch, these are:

8899465bec27 tpm2_create: fix -I - option argument
e13a2b0d71ad tpm2_quote: drop if 0 code
01054bc7d3a0 tpm2_quote: drop -o option
5bdab63d0a1c man/tpm2_quote: fix whitespace error
7eb26d482c9f man/tpm2_quote: add missing -s option
ce7c160cdd17 tpm2_rsaencrypt: support -I as an argument

**Comment by martinezjavier** [comment]
@williamcroberts perfect, please let me know if you need any help from me. I'm only reporting things and nof taking action to avoid step into your toes.

**Comment by williamcroberts** [comment]
```
applied: 8899465 tpm2_create: fix -I - option argument
applied: e13a2b0 tpm2_quote: drop if 0 code
applied: 01054bc tpm2_quote: drop -o option
applied: 5bdab63 man/tpm2_quote: fix whitespace error
applied: 7eb26d4 man/tpm2_quote: add missing -s option
applied: ce7c160 tpm2_rsaencrypt: support -I as an argument
```

**Comment by williamcroberts** [comment]
The unit tests depend on: https://github.com/intel/tpm2-tss/pull/614

I'm hopinh @flihp will take it for 1.3 TSS release.

**Comment by martinezjavier** [comment]
@williamcroberts since you think that we should just remove the tpm2_import tool for 3.X, you might want to squash the following commit to https://github.com/intel/tpm2-tools/pull/613/commits/9ea2cbd7bc92ffc1bb865b4861d69e03d44d7b36 ("HACK: don't build and test tpm2_import"):

https://github.com/martinezjavier/tpm2-tools/commit/03ca9d2a7af5fa95331ec14aa42b5b7c18591017 ("fixup! HACK: don't build and test tpm2_import")

That deletes all traces of the tpm2_import tool (man page, source code, change log entry, etc).

Also, don't forget to drop commit https://github.com/williamcroberts/tpm2.0-tools/commit/812fbb51c6f1412ac0ab027b8cb2b69aa5fbbafc ("[REVERTME] test_tpm2_activecredential is failing") before merging, since I see that's still in your 3.X branch.

**Comment by martinezjavier** [comment]
> @williamcroberts since you think that we should just remove the tpm2_import tool for 3.X, you might want to squash the following commit to 9ea2cbd ("HACK: don't build and test tpm2_import"):

Probably also a good idea to change the subject line to remove the HACK prefix and amend the commit message a little bit.

**Comment by martinezjavier** [comment]
@williamcroberts awesome, I don't think we don't have anything left for 3.X, right? Besides more testing and fixing any issues that arise of course.

**Comment by williamcroberts** [comment]
@martinezjavier I think this is it. I was going to cut an rc0 so folks can kick the tires and report issues.

**Pull request merged**
