### PR TITLE
 Update SetCmdAuths and GetRspAuths to new parameter type

### PR DESCRIPTION
**Pull request by AndreasFuchsSIT**
This implements the corresponding part to tpm2-tss's https://github.com/intel/tpm2-tss/pull/634

Note that this is actually just 1 commit, but ontop of PR #644 

P.S. This will not work on travis, since the version of tpm2-tss is too old

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
Rebased...

**Comment by tstruk** [comment]
@AndreasFuchsSIT Thanks!
@williamcroberts are you ok with this PR? I would like to take merge https://github.com/intel/tpm2-tss/pull/634

**Comment by williamcroberts** [comment]
Go for it, I have https://github.com/intel/tpm2-tools/pull/645 I can rebase.

**Comment by williamcroberts** [comment]
I rebased this here, no conflicts:
https://github.com/intel/tpm2-tools/pull/677

Im going to close this so I have a branch I can push too in-case something needs updating. Thanks @AndreasFuchsSIT for the patch.

**Pull request closed without merging**
