### PR TITLE
Update tpm2_pcrlist.c

### PR DESCRIPTION
**Pull request by yunusemreayhan**
Unsinged int signed int comparison error, on line 257,
please fix.

### CODE REVIEW

**Comment by snits** [comment]
Isn't sizeofSelect a UINT8?

**Comment by yunusemreayhan** [comment]
```
libtool: link: warning: library `/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib/libtcti-socket.la' was moved.
libtool: link: warning: library `/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib/libsapi.la' was moved.
libtool: link: warning: library `/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib/libtcti-socket.la' was moved.
libtool: link: warning: library `/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib/libsapi.la' was moved.
/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib/libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
  CC     tools/tpm2_pcrextend.o
  CCLD   tools/tpm2_pcrextend
libtool: link: warning: library `/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib/libtcti-socket.la' was moved.
libtool: link: warning: library `/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib/libsapi.la' was moved.
libtool: link: warning: library `/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib/libtcti-socket.la' was moved.
libtool: link: warning: library `/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib/libsapi.la' was moved.
/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib/libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
  CC     tools/tpm2_pcrlist.o
cc1: warnings being treated as errors
tools/tpm2_pcrlist.c: In function 'show_pcr_values':
tools/tpm2_pcrlist.c:257: error: comparison between signed and unsigned
make[3]: *** [tools/tpm2_pcrlist.o] Error 1
make[2]: *** [/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/build/tpmtsstools-3.0.2/.stamp_built] Error 2
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/change/maxim-ic/lde-3.0/TREE/user/buildroot'
make: *** [rootfs-build] Error 2
make: Leaving directory `/home/change/maxim-ic/lde-3.0'
ldecmd build usip-0.2.3: *** ERROR 2, command failed: make -C /home/change/maxim-ic/lde-3.0 rootfs
/home/change/bin/ldecmd v1.0.2: *** ERROR 2, command failed: build rootfs
/home/change/maxim-ic/lde-3.0/user/buildroot/package
```
here is actual compiler error.

**Comment by yunusemreayhan** [comment]
i have updated request to UINT8 now.

**Comment by snits** [comment]
@yunusemreayhan what compiler (and version) was being used when you see this error?

**Comment by yunusemreayhan** [comment]
#749 same environment with this issue.

**Comment by snits** [comment]
Did the error go away with the change to UINT8?

**Comment by yunusemreayhan** [comment]
yes it did

**Comment by snits** [comment]
If you wouldn't mind doing a test, what happens if the pcr_id is left as UINT32 and the comparison in the for loop is changed to:

`
pcr_id < ctx.pcr_selections.pcrSelections[i].sizeofSelect * 8u
`

**Comment by yunusemreayhan** [comment]
yes, that way it worked though.

```
        ...
        UINT32 pcr_id;
        for (pcr_id = 0; pcr_id < ctx.pcr_selections.pcrSelections[i].sizeofSelect * 8u; pcr_id++) {
            if (!is_pcr_select_bit_set(&ctx.pcr_selections.pcrSelections[i],
                    pcr_id)) {
                    ...
```

**Pull request merged**
