### PR TITLE
tpm2_clear: add tool

### PR DESCRIPTION
**Pull request by emmanuel-deloget**
Add a (crude) tpm2_clear tool which is used to clear the TPM2 and
restore it to a nearly blank state.

### CODE REVIEW

**Comment by martinezjavier** [comment]
@emmanuel-deloget the tpm2_takeownership already has a `-c` option which I thought was used to clear the TPM, what's the difference between that option and this new tool?

**Comment by emmanuel-deloget** [comment]
@martinezjavier tpm2_takeownership -c does a TPM2_Clear with TPM2_RH_LOCKOUT, this one does a TPM2_RH_PLATFORM which does not fail when you're DA-locked.

**Comment by martinezjavier** [comment]
@emmanuel-deloget ah, I see. Wonder if we should either add this option to tpm2_takeownership or make tpm2_clear allow to either clear using either TPM2_RH_PLATFORM or TPM2_RH_LOCKOUT.

Also, IIUC your tool assumes that there is an empty password for the platform hierarchy but AFAICT this is usually not the case. I see that the platform hierarchy authorization is set to a random value at startup by the firmware.

Probably that's something that should be documented in the tool man page.

**Comment by emmanuel-deloget** [comment]
@martinezjavier both -p and -P are already taken on tpm2_takeownership :) More seriously, thet fact that we work on the platform hierarchy here would be at odd with the goal of tpm2_takeowership (that' s how I conseive it but I may be wrong). 

About the empty password: as I said in my PR, this is a crude version of the program (I needed it, so I built it). Adding a lockoutAuth password should not be too difficult. In my tests, such a password was not needed (I used it to bypass the lockoutAuth in order to restore the tpm2 in a working state after I made a few errors). 

Also, I find weird that this password may be needed -- I cannot find this in the spec, so if you have a pointer, I'll happily read it. If the firmware really set it to a random value at startup, that would make this command entirely non-fonctionnal (as I have no way to retrieve this password). And of course, clearing the platform hierarchy is already PP-protected.

**Comment by martinezjavier** [comment]
@emmanuel-deloget I'm not saying your tool is not needed, in fact I like it since the convention is to have the tools named after the TPM2 command code. Son for consistency with the other tools `tpm2_clear` is much better than `tpm2_takeownership -c` IMHO.

I just don't want to have two ways to do similar things in the tools, so users may be confused (as I was) about the difference between `tpm2_takeownsership -c` and `tpm2_clear`.

Now, going back to the password issue. I get the following when trying your tool on my Intel PTT TPM2 implemented in the ME:

```
$ tpm2_clear                                                 
ERROR: Tss2_Sys_Clear failed: 0x9a2                    
$ tpm2_rc_decode 0x9a2                                               
error layer                
  hex: 0x0                 
  identifier: TSS2_TPM_RC_LAYER                        
  description: Error produced by the TPM               
format 1 error code        
  hex: 0x22                
  identifier: TPM2_RC_BAD_AUTH                         
  description: authorization failure without DA implications                                                   
session                    
  hex: 0x100               
  identifier: TPM2_RC_1    
  description:  (null)
```

Which is caused by the fact that the platform hierarchy has an authorization password set. My understanding is that's true for most TPM2 out there.

This is another example: https://github.com/intel/tpm2-tss/issues/354

**Comment by williamcroberts** [comment]
I would be OK with splitting out tpm2_takeownership as it's using two tpm functions that actually change this (i'm ok with reading public data in a tool to get a default size or something).
tpm2_takeownership could be tpm2_clear and tpm2_changeauth (or something like that).

**Comment by emmanuel-deloget** [comment]
@williamcroberts @martinezjavier So to get this straight : 

1) remove option -c on tpm2_takeownership
2) rename tmp2_takeowership to tpm2_changeauth
3) make a tpm2_clear with the following characteristics
   - allow to work on the platform or lockout hierarchy
   - allow a (lockout) password to be specified

Am I correct?

While I'm at it, the tpm2_clear tool might also be a good place to implement TPM2_ClearControl() (that would disallow TPM2_Clear()). How does that sound?

**Comment by martinezjavier** [comment]
@emmanuel-deloget sounds good to me. My only doubt now is if we should have a separate tpm2_clearcontrol tool... we have for example tpm2_nvreadlock and tpm2_nvread as separate tools.

But I don't really have a strong opinion on that, so whatever @williamcroberts and you decide.

**Comment by williamcroberts** [comment]
@martinezjavier @emmanuel-deloget let's keep them seperate tools for clearcontrol and clear, since it does fall in line with nvread and nvreadlock.

**Comment by williamcroberts** [comment]
Issue created for adding a clearlock tool: https://github.com/intel/tpm2-tools/issues/710

**Pull request closed without merging**
